### ISSUE TITLE
Definition of default pins

### ISSUE THREAD

**Issue by omikron88** [pschatzmann/pico-arduino#13]
Hello,
It work fine now. Thank you.
Is it possible to define the default uart, spi and i2c pins in project's CMakeLists.txt or in some top-level header file?

**Comment by pschatzmann** [comment]
Not for the time being. 
I could use some #defines - but since this  would require to rebuild and re-deply of the arduino library itself, everytime a pin assignment is changed - I don't consider this a good solution.

The current concept is, that if the default pins are not fitting, you can define your own in the begin method...

**Comment by pschatzmann** [comment]
After some thoughts, I decided to get rid of the prebuilt library and have all the code complied as part of the sketch.
You can find an example in https://github.com/pschatzmann/pico-arduino/tree/main/examples/hallo_world_serial_define_pins
